### ISSUE TITLE
adding renderings (pdf, etc.)

### ISSUE THREAD

**Issue by eroux** [ArchiveLabs/iiif.archivelab.org#39] opened 2019-07-15 15:55 UTC
It would be nice to add some [renderings](https://iiif.io/api/presentation/2.1/#rendering) in the manifest, such as the PDF export for instance. What's the method to know if it's possible to export as pdf or not?

**Comment by glenrobson** [comment] 2023-03-10 09:19
I think this is now a duplication of https://github.com/ArchiveLabs/iiif.archivelab.org/issues/71

**Comment by eroux** [comment] 2023-03-10 09:26
the issues are similar enough to be merged if you want, sure

**Comment by benwbrum** [comment] 2024-01-11 22:43
Duplicate of #71

**Closed by benwbrum** 2024-01-11 22:43 UTC
Labels: duplicate
